name: example
description: Example.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  cloud_firestore:
  freezed_annotation:
  json_annotation:
  json_converter_helper:
    path: ..
dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  pedantic_mono:
